import type {
  NavLink,
  NavConfig,
  Job,
  Stat,
  Course,
  Testimonial,
  CommunityResource,
} from "@/types";

export const NAV_CONFIG: NavConfig = {
  main: [
    { label: "首页", href: "/" },
    { label: "课程", href: "#courses" },
    { label: "学员故事", href: "#testimonials" },
    // { label: "社区", href: "#community" },
    // { label: "企业合作", href: "#enterprise" },
  ],
  footer: {
    产品: [
      { label: "AI 工程师课程", href: "#courses" },
      { label: "大模型微调实战", href: "#courses" },
      { label: "RAG 应用开发", href: "#courses" },
      { label: "企业定制培训", href: "#enterprise" },
    ],
    资源: [
      { label: "技术博客", href: "#community" },
      { label: "开源项目", href: "#community" },
      { label: "开发者社区", href: "#community" },
      { label: "学习路线图", href: "#community" },
    ],
    公司: [
      { label: "关于我们", href: "#about" },
      { label: "讲师团队", href: "#about" },
      { label: "合作伙伴", href: "#enterprise" },
      { label: "联系我们", href: "#enterprise" },
    ],
  },
  social: [
    { icon: "github", href: "https://github.com", label: "GitHub" },
    { icon: "twitter", href: "https://twitter.com", label: "Twitter" },
    { icon: "youtube", href: "https://youtube.com", label: "YouTube" },
    { icon: "discord", href: "https://discord.com", label: "Discord" },
  ],
};

export const JOBS: Job[] = [
  {
    id: "1",
    company: "字节跳动",
    title: "AI 工程师",
    salary: "40-70K",
    location: "北京",
    type: "全职",
  },
  {
    id: "2",
    company: "阿里巴巴",
    title: "大模型研究员",
    salary: "50-90K",
    location: "杭州",
    type: "全职",
  },
  {
    id: "3",
    company: "腾讯",
    title: "LLM 应用开发",
    salary: "35-60K",
    location: "深圳",
    type: "全职",
  },
  {
    id: "4",
    company: "百度",
    title: "NLP 算法工程师",
    salary: "30-55K",
    location: "北京",
    type: "全职",
  },
  {
    id: "5",
    company: "华为",
    title: "AI 平台架构师",
    salary: "45-80K",
    location: "深圳",
    type: "全职",
  },
  {
    id: "6",
    company: "商汤科技",
    title: "计算机视觉工程师",
    salary: "35-65K",
    location: "上海",
    type: "全职",
  },
  {
    id: "7",
    company: "OpenAI",
    title: "Research Engineer",
    salary: "$200-400K",
    location: "远程",
    type: "全职",
  },
  {
    id: "8",
    company: "Anthropic",
    title: "ML Engineer",
    salary: "$180-350K",
    location: "远程",
    type: "全职",
  },
];

export const STATS: Stat[] = [
  { id: "1", label: "学员人数", value: 12800, suffix: "+" },
  { id: "2", label: "精品课程", value: 86, suffix: "+" },
  { id: "3", label: "就业率", value: 96, suffix: "%" },
  { id: "4", label: "平均薪资涨幅", value: 45, suffix: "%" },
];

export const COURSES: Course[] = [
  {
    id: "1",
    title: "21天 AI 实战营",
    subtitle: "// AI 极速开发 · 创业变现",
    description: "Seven 亲自直播授课 · 3周跑通「AI开发→全球比赛拿奖」闭环",
    duration: "21 天",
    difficulty: "进阶",
    price: "¥2999",
    originalPrice: "¥5999",
    priceLabel: "早鸟价",
    badge: "NEW",
    highlights: ["真实案例：用 AI 单人参赛全球黑客松，3天 Demo 到手 $2000"],
    features: [
      { text: "AI 极速开发工作流，超60%课时直播+视频+实战驱动" },
      { text: "2大副业级Agent背书，手搓预测市场监控引擎" },
      { text: "全球黑客松参赛 SOP 与夺金实战" },
      { text: "对赌福利：参赛获奖返学费" },
    ],
    ctaText: "了解实战营详情 →",
    ctaVariant: "outline",
    footerNote: "适合有代码基础、想用 AI 业余时间赚美金的开发者",
  },
  {
    id: "2",
    title: "100天私教班·全链路转型",
    subtitle: "// 全职远程 · 深度陪跑",
    description: "平均3~4个月，从零到拿下海外 $4000+ 全职远程 Offer",
    duration: "100 天",
    difficulty: "专家",
    price: "¥15999",
    priceLabel: "试用期包过",
    badge: "推荐",
    features: [
      { text: "包含实战营全部内容", checked: true },
      { text: "EVM / Solidity / Go 深度课", checked: true },
      { text: "4v1 导师团全链路陪跑", checked: true },
      { text: "简历优化 + 模拟面试 + 内推", checked: true },
      { text: "主网级商业项目完整源码", checked: true },
      { text: "Discord 校友内推网络终身权益", checked: true },
    ],
    highlights: [
      "适合想拿下 $4000+ 全职远程 Offer、彻底转型  核心开发岗的程序员。当 AI 碰到底层协议安全和高并发瓶颈时，你需要的是真正的硬功夫。",
    ],
    ctaText: "立即咨询，规划转型路线",
    ctaVariant: "primary",
    footerNote: "完成可抵扣开课学费",
  },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: "1",
    name: "吴同学",
    role: "Golang 后端工程师",
    company: "某互联网大厂",
    avatar: "/images/avatar-1.jpg",
    quote:
      "感谢老师们的耐心指导培训，才能顺利拿到 offer！从 Java 转到 Go，跨度很大但课程体系非常完整。",
    rating: 5,
    course: "AI 全栈工程师训练营",
    education: "本科",
    techFrom: "Java",
    techTo: "Golang 后端",
    duration: "3.5 个月",
    salary: "7000U+",
    joinDate: "2025/10 初",
    landDate: "2026/1 底",
  },
  {
    id: "2",
    name: "许同学",
    role: "AI开发工程师",
    company: "某 AI 项目方",
    avatar: "/images/avatar-2.jpg",
    quote:
      "规划的学习路线非常清晰，谢谢大家的帮助。从后端转AI，现在薪资翻了快一倍。",
    rating: 5,
    course: "RAG 应用开发从零到一",
    education: "本科",
    techFrom: "后端",
    techTo: "AI",
    duration: "4 个月",
    salary: "39k+",
    joinDate: "2025/7 底",
    landDate: "2025/11 中",
  },
  {
    id: "3",
    name: "王同学",
    role: "AI 算法工程师",
    company: "某 AI 独角兽",
    avatar: "/images/avatar-3.jpg",
    quote:
      "大模型微调实战课的实操项目非常接近真实业务场景，直接帮助我通过了技术面试。",
    rating: 5,
    course: "大模型微调实战课",
    education: "硕士",
    techFrom: "Python 数据分析",
    techTo: "LLM 微调",
    duration: "5 个月",
    salary: "55k+",
    joinDate: "2025/4",
    landDate: "2025/9",
  },
];

export const COMMUNITY_RESOURCES: CommunityResource[] = [
  {
    id: "1",
    title: "GitHub 开源",
    description: "所有课程代码、示例项目和学习资源",
    href: "https://github.com",
    icon: "github",
  },
  {
    id: "2",
    title: "开发者社区",
    description: "与 12000+ 学员实时交流技术问题",
    href: "https://discord.com",
    icon: "discord",
  },
  {
    id: "3",
    title: "技术博客",
    description: "每周发布 AI 前沿技术深度解析",
    href: "#",
    icon: "blog",
  },
  {
    id: "4",
    title: "Newsletter",
    description: "订阅获取最新 AI 资讯与学习资源",
    href: "#",
    icon: "newsletter",
  },
  {
    id: "5",
    title: "线下活动",
    description: "定期举办技术分享会与黑客松",
    href: "#",
    icon: "meetup",
  },
  {
    id: "6",
    title: "API 文档",
    description: "完整的课程平台 API 接入文档",
    href: "#",
    icon: "docs",
  },
];
